{
 "title": "Weather Pipeline Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total de Eventos Exitosos",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "targets": [
    { "expr": "weather_events_total" }
   ]
  },
  {
   "title": "Total de Errores",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "targets": [
    { "expr": "weather_events_errors_total" }
   ]
  },
  {
   "title": "Tasa de Envío (por min)",
   "type": "gauge",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(weather_events_total[1m]) * 60"
    }
   ]
  },
  {
   "title": "Eventos Climáticos (Rendimiento por min)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 16, "h": 8 },
   "targets": [
    {
     "expr": "rate(weather_events_total[1m]) * 60",
     "legendFormat": "Eventos por minuto"
    }
   ]
  }
 ]
}